# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

twin_cpp <- function(data, r, u1, leaf_size = 8L) {
    .Call(`_twinning_twin_cpp`, data, r, u1, leaf_size)
}

multipletS3_cpp <- function(data, r, u1, leaf_size = 8L) {
    .Call(`_twinning_multipletS3_cpp`, data, r, u1, leaf_size)
}

energy_cpp <- function(data, points) {
    .Call(`_twinning_energy_cpp`, data, points)
}

